# 上传通道 线路A1 线路A2 线路A3 自定义
# 以js结尾可读取js代码构建自定义线路,例如test.js
uploader: "线路A2"
# 上传并发 并发数量会根据分片大小自动调整,基于1mb,如果并发为10,分片为2mb,实际并发数量计算结果为5
upload_task: 10
# 上传失败重试
upload_retry: 10
#下载并发 并发数量会根据分片大小自动调整,基于1mb,如果并发为10,分片为2mb,实际并发数量计算结果为5
download_task: 5
# 分片大小,kb,最大20mb
chunk_size: 1024
# 端口
port: 4719
host: "0.0.0.0"
# http自定义线路url
custom_url: ""
# http自定义线路referer
custom_referer: ""
webdav_path: "data.mix_dav"
# 密码 留空为取消密码
password: ""
history: "history.mix_list"
